//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionEtudiat.entityframework
{
    using System;
    using System.Collections.Generic;
    
    public partial class classe
    {
        public int id { get; set; }
        public string libelle { get; set; }
        public int nbre_etudiant { get; set; }
    
        public virtual classe classe1 { get; set; }
        public virtual classe classe2 { get; set; }
        public virtual classe classe11 { get; set; }
        public virtual classe classe3 { get; set; }
    }
}
