//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionEtudiat.entityframework
{
    using System;
    using System.Collections.Generic;
    
    public partial class personne
    {
        public int id { get; set; }
        public string nom_complet { get; set; }
        public string type { get; set; }
        public string tuteur { get; set; }
        public string grade { get; set; }
        public string modules { get; set; }
        public string matricule { get; set; }
        public string login { get; set; }
        public string pwd { get; set; }
        public Nullable<int> classe_id { get; set; }
    }
}
